language: cpp

before_install:
  - git clone https://github.com/google/googletest.git

install:
  - gem install coveralls-lcov

script:
  - make GTEST_DIR=googletest/googletest

after_success:
  - ./Tests
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' 'usr/*' '*gtest*'  --output-file coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info

notifications:
  email:
    on_success: change
    on_failure: change
