language: cpp

before_install:
  - git clone https://github.com/google/googletest.git

install:  
  - sudo apt-get install -y lcov
  
script:
  - make GTEST_DIR := googletest/googletest

notifications:
  email:
    on_success: change
    on_failure: change
