language: cpp

before_install:
  - pip install --user cpp-coveralls
  - git clone https://github.com/google/googletest.git

install:  
  - sudo apt-get install -y lcov
  
script:
  - make GTEST_DIR=googletest/googletest
  
after_success:
  - ./Tests
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
  email:
    on_success: change
    on_failure: change
