language: cpp

before_install:
  - git clone https://github.com/google/googletest.git

install:
  - sudo apt-get install lcov
  - gem install coveralls-lcov

script:
  - cd src/tests/
  - make GTEST_DIR=../../googletest/googletest

after_success:
  - make exec
  - make coverage
  - coveralls-lcov build/coverage.info

notifications:
  email:
    on_success: change
    on_failure: change
