name: Build+Test

on: [push]

jobs:
  build:
    name: Build library
    runs-on: ubuntu-18.04
    steps:
      - name: Pull the repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: false
      - name: Prepare env
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      - name: Build
        run: |
          cd src/
          make CPP=clang-9 CXX=clang++-9
  test:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
       - name: Pull the repository and submodules
         uses: actions/checkout@v1
         with:
           fetch-depth: 1
           submodules: true
       - name: Prepare env
         run: |
           sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
       - name: Build
         run: |
           cd src/tests
           make pre-build
           make CPP=clang-9 CXX=clang++-9
           make exec
  format:
    name: Code formatting
    runs-on: ubuntu-18.04
    steps:
       - name: Pull the repository
         uses: actions/checkout@v1
         with:
           fetch-depth: 1
           submodules: false
       - name: Prepare env
         run: |
           sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
           sudo apt install clang-format-9
       - name: Build
         run: |
           cd src
           make format CF_FAIL_ON_DIFF=1 CLANG_FORMAT=clang-format-9
